"""deleted field in user model

Revision ID: b2b472dd16ac
Revises: 2aa9a2a1f908
Create Date: 2023-10-20 14:56:03.549036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2b472dd16ac'
down_revision = '2aa9a2a1f908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', mysql.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
